backend:
  name: github
  branch: dev
  repo: SpiritbloomPro/new-spiritbloom

site_url: https://new.spiritbloom.pro
logo :
  src: https://new.spiritbloom.pro/img/Spiritbloom.png
  show_in_header: true

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          width: 2048
          height: 2048
        svg:
          optimize: true
  stock_assets:
    providers: []

collections:
- name: general
  label: "General Guide"
  folder: general
  icon: star
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number}
- name: preservation
  label: "Preservation Guide"
  folder: preservation
  icon: nest_eco_leaf
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number}
- name: holy-paladin
  label: "Holy Paladin Guide"
  folder: holy-paladin
  icon: brightness_5
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number}
- name: restoration-shaman
  label: "Restoration Shaman Guide"
  folder: restoration-shaman
  icon: water_drop
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number}
- name: blog
  label: "Blog"
  folder: blog
  icon: article
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors"
      widget: "list"
- name: config
  label: Configurations
  icon: edit_square
  editor:
    preview: false
  files:
    - name: authors
      label: Authors
      file: blog/authors.yml
      delete: false
      editor:
        preview: false
      fields:
        - name: harrek
          label: Harrek
          widget: object
          fields:
            - name: name
              label: Name
              widget: string
            - name: title
              label: Title
              widget: string
            - name: url
              label: URL
              widget: string
            - name: image_url
              label: Image
              widget: string
            - name: description
              label: Description
              widget: text
            - name: page
              label: Page
              widget: hidden
              default: true
    - name: evoker-spells
      label: Evoker
      file: static/spells/evoker.json
      fields:
        - name: body
          label: Spells
          widget: code
          output_code_only: true
          allow_language_selection: false
          root: true

singletons:
